### ISSUE TITLE
Pin icon now turns golden rather than blue when clicked

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#23]
I think this icon used to display blue like Inbox, a few days/merges ago.

<img width="188" alt="Screen Shot 2019-04-09 at 2 52 10 PM" src="https://user-images.githubusercontent.com/5100126/55806321-efd9af00-5ad7-11e9-851f-d1368c80bc11.png">

**Comment by joeytroy** [comment]
@russelldc this is normal behavior. You need to go to settings and change to the blue star from the gold star. Since I changed the pins to color coordinate with the stars here is an example of the blue pin and star.

![image](https://user-images.githubusercontent.com/1558465/55904155-6c2dca00-5b8c-11e9-8792-07591730b1dd.png)

![image](https://user-images.githubusercontent.com/1558465/55904183-7f409a00-5b8c-11e9-9a25-2e9c1031c0e1.png)
![image](https://user-images.githubusercontent.com/1558465/55904186-82d42100-5b8c-11e9-8eaa-560bfa77b323.png)

**Comment by russelldc** [comment]
@g60madman Ahh, understood. Might be unexpected behavior for some users, I guess we'll see if anyone complains.
