### ISSUE TITLE
Order of mouseover options doesn't match Inbox.

### ISSUE THREAD

**Issue by digitalneoplasm** [boukestam/inbox-in-gmail#54]
The order of the hover-over links which appear over messages does not match what is expected in Inbox. I still have an Inbox tab open (who knows for how much longer), so I can show the comparison:

Inbox: 
![image](https://user-images.githubusercontent.com/1452510/56319903-db796000-6130-11e9-9467-dad4f07e2aea.png)

Inbox-in-Gmail:
![image](https://user-images.githubusercontent.com/1452510/56319917-eb913f80-6130-11e9-8533-c330abb0b963.png)

I keep almost clicking the wrong thing and it's a bit jarring :).

**Comment by russelldc** [comment]
> I keep almost clicking the wrong thing and it's a bit jarring

That's a good point. Muscle memory is very powerful!

**Comment by abasiri** [comment]
What are your thoughts on this. I found that I was primarily messing up when I wanted to click the Done button, this change should address that. i can't change the pin location though, since it's where the yellow pin icon appears, when an email is pinned.

![image](https://user-images.githubusercontent.com/708414/56844990-c4441c00-686e-11e9-8476-544d89b0e9c8.png)

**Comment by russelldc** [comment]
@abasiri Makes sense to me. I think leaving the pin where it is is fine.
Unless you've already fixed this since your screenshot, it looks like there should be more spacing between the Done icon and the Pin.

What do you think, @digitalneoplasm ?

**Comment by digitalneoplasm** [comment]
I agree, I think this is great! The Done button was also my primary concern! Thanks!
