### ISSUE TITLE
Link to Chrome Webstore is broken in README

### ISSUE THREAD

**Issue by Muffo** [boukestam/inbox-in-gmail#77]
I cannot find the extension on the Chrome Webstore anymore. The link in the README appears to be broken.

**Comment by russelldc** [comment]
@Muffo See issue #69 Extension removed from chrome store

Google removed the extension about a week ago, and sent a vague explanation email to @boukestam 

We've since changed the name to Inbox Reborn, updated the description, put together new screenshots and a new icon that doesn't use the Gmail icon. I think Bouke has re-submitted it as of yesterday, waiting for approval now.

If you need to install it now, clone the repo and load it as an unpacked extension in Chrome/Firefox. There's been a lot of updates since the last published version.

**Comment by Muffo** [comment]
That's unfortunate! Thanks for the reply.

Maybe you could keep this ticket open as a "reminder" that the README needs to be updated once the new extension is published.

**Comment by russelldc** [comment]
I'll go add a disclaimer to the readme now, good point.
