### ISSUE TITLE
Reminder not getting my current email address

### ISSUE THREAD

**Issue by arormoser** [boukestam/inbox-in-gmail#91]
Getting my current email address was not working for me. I change this and start working again:

Line 40 Replace this:
const getMyEmailAddress = () => document.querySelector('.gb_lb') ? document.querySelector('.gb_lb').innerText : '';
for this:
const getMyEmailAddress = () => document.querySelector('.gb_hb') ? document.querySelector('.gb_hb').innerText : '';

Also first time I create a reminder focus was not on the Body, I added this and start working:
Line 770 add this 2 lines (before body.focus()):
			triggerMouseEvent(body, 'mousedown');
			triggerMouseEvent(body, 'mouseup');

**Comment by mdesson** [comment]
Hi, has there be any movement on this issue? I'm having the same problem and this would make for a great PR to fix the problem. If not, I'd be open to put one up. I just discovered the extension today and it's great!

Edit: A quick note that the solution in the original issue has stopped working. However, this does work (`qb` instead of `hb`):
```js
 const getMyEmailAddress = () => document.querySelector('.gb_qb') ? document.querySelector('.gb_qb').innerText : '';
```

I'm not sure if it's because of my environment or if there's been an update. However, we could chain the ternaries to try both or use a simple if/else or swtich statement, wahtever is cleanest.

**Comment by mdesson** [comment]
I've put in a PR to fix this issue: https://github.com/boukestam/inbox-in-gmail/pull/96
